// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOl8Yasvfwtm__qIZgFL8b9gv6jKnYgTU',
    appId: '1:606272747026:web:41357e8ad142f9ef440acb',
    messagingSenderId: '606272747026',
    projectId: 'mothercompany',
    authDomain: 'mothercompany.firebaseapp.com',
    storageBucket: 'mothercompany.appspot.com',
    measurementId: 'G-6HQYY03T8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKdHuKD4pDvkPBTj5cEoxFSeszZhgOEmU',
    appId: '1:606272747026:android:2151ef8d8d19efd9440acb',
    messagingSenderId: '606272747026',
    projectId: 'mothercompany',
    storageBucket: 'mothercompany.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACicLdRF81i9OvtqVsoNlIR0Mu3zRb39U',
    appId: '1:606272747026:ios:c19abfdbed28562e440acb',
    messagingSenderId: '606272747026',
    projectId: 'mothercompany',
    storageBucket: 'mothercompany.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACicLdRF81i9OvtqVsoNlIR0Mu3zRb39U',
    appId: '1:606272747026:ios:c19abfdbed28562e440acb',
    messagingSenderId: '606272747026',
    projectId: 'mothercompany',
    storageBucket: 'mothercompany.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOl8Yasvfwtm__qIZgFL8b9gv6jKnYgTU',
    appId: '1:606272747026:web:089216ebcc2d3808440acb',
    messagingSenderId: '606272747026',
    projectId: 'mothercompany',
    authDomain: 'mothercompany.firebaseapp.com',
    storageBucket: 'mothercompany.appspot.com',
    measurementId: 'G-KXLYM3F3ZJ',
  );

}